<script>
	import ShareWith from '../ShareWith.svelte';
	import Hoverable from './Hoverable.svelte';

	export let post;
	console.log({ post });
</script>

{#if post && post.encryptedData}
	<h3>{post.tag}</h3>
	<Hoverable let:hovering={active}>
		<div class:active>
			encryptedData:
			<a
				href="https://dweb.link/api/v0/dag/get?arg={post.encryptedData.toString()}"
				target="_blank"
			>
				{post.encryptedData.toString()}</a
			><br />

			{#if active}
				<p>📂 Decrypted Data:</p>
				<div>
					<!-- Generated by parent's parent in the slot  -->
					<slot />
				</div>
			{:else}
				<p>🔒 Click to decrypt!</p>
			{/if}
		</div>
		<ShareWith tag={post.tag} />
	</Hoverable>
	<small>{new Date(post.timestamp).toLocaleString()}</small><br />
{/if}

<style>
	h3 {
		margin: 1.17em 0em 0.5em 0em;
	}
	div {
		padding: 1em;
		margin: 0 0 1em 0;
		background-color: #eee;
	}

	.active {
		background-color: rgba(76, 175, 79, 0.2);
		color: rgb(53, 53, 53);
	}
</style>
